import ui

html = ("<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>Yahtzee Strategy Helper</title>"
"<style>"
"* { margin: 0; padding: 0; box-sizing: border-box; }"
"body { font-family: 'Arial Black', Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 16px; color: #333; }"
".container { max-width: 1400px; margin: 0 auto; display: grid; grid-template-columns: 1fr 330px; gap: 16px; }"
".game-area { background: white; border-radius: 12px; padding: 18px; box-shadow: 0 6px 16px rgba(0,0,0,0.2); }"
".sidebar { display: flex; flex-direction: column; gap: 16px; }"
".recommendations-top { background: linear-gradient(135deg, #fff9c4 0%, #fff59d 100%); border-radius: 12px; padding: 14px 16px; margin-bottom: 12px; box-shadow: 0 4px 10px rgba(255, 193, 7, 0.25); border: 2px solid #ffd54f; }"
".recommendations-top h2 { color: #f57c00; margin-bottom: 8px; text-align: center; font-size: 1.3em; }"
"h1 { text-align: center; color: #764ba2; font-size: 2em; margin-bottom: 8px; }"
".roll-info { text-align: center; font-size: 1.05em; color: #667eea; margin-bottom: 12px; font-weight: bold; }"
".dice-container { display: flex; justify-content: center; gap: 10px; margin: 18px 0 8px; flex-wrap: wrap; }"
".die-wrapper { display: flex; flex-direction: column; align-items: center; gap: 4px; }"
".die { width: 64px; height: 64px; background: white; border: 2px solid #333; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 2.2em; font-weight: bold; cursor: pointer; transition: transform 0.15s; box-shadow: 0 2px 4px rgba(0,0,0,0.2); user-select: none; }"
".die:active { transform: scale(0.96); }"
".die.kept { background: #ffd700; border-color: #ff6b6b; }"
".die.empty { background: #f0f0f0; border: 2px dashed #ccc; color: #ccc; }"
".hold-toggle { padding: 3px 8px; font-size: 0.7em; border-radius: 999px; border: 1px solid #764ba2; background: #fff; cursor: pointer; transition: background 0.15s; }"
".hold-toggle.held { background: #764ba2; color: #fff; border-color: #764ba2; }"
".controls { display: flex; justify-content: center; flex-wrap: wrap; gap: 8px; margin: 12px 0; }"
"button { padding: 10px 14px; font-size: 0.95em; font-weight: bold; border: none; border-radius: 8px; cursor: pointer; transition: transform 0.15s; box-shadow: 0 3px 6px rgba(0,0,0,0.18); }"
"button:active { transform: scale(0.97); }"
".roll-btn { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }"
".roll-btn:disabled { background: #ccc; cursor: not-allowed; box-shadow: none; }"
".new-game-btn { background: #ff6b6b; color: white; }"
".clear-btn { background: #ffa726; color: white; }"
".scorecard { background: white; border-radius: 12px; padding: 14px; box-shadow: 0 6px 16px rgba(0,0,0,0.2); }"
".scorecard h2 { color: #764ba2; margin-bottom: 10px; text-align: center; }"
".score-section { margin-bottom: 14px; }"
".score-section h3 { color: #667eea; margin-bottom: 6px; font-size: 0.9em; }"
".score-row { display: flex; justify-content: space-between; padding: 6px 8px; margin: 3px 0; border-radius: 5px; font-size: 0.9em; }"
".score-row.available { background: #e8f5e9; cursor: pointer; border: 1px solid #4caf50; }"
".score-row.filled { background: #f0f0f0; }"
".score-name { font-weight: bold; }"
".score-value { color: #667eea; font-weight: bold; }"
".bonus-tracker { background: linear-gradient(135deg, #ffd700 0%, #ffed4e 100%); padding: 10px; border-radius: 10px; margin: 10px 0; text-align: center; font-size: 0.9em; }"
".bonus-progress { background: white; height: 16px; border-radius: 10px; margin: 6px 0; overflow: hidden; border: 1px solid #333; }"
".bonus-fill { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); height: 100%; width: 0%; transition: width 0.2s; }"
".recommendation { background: white; padding: 10px 12px; margin: 8px 0; border-radius: 8px; border-left: 4px solid #4caf50; box-shadow: 0 2px 6px rgba(0,0,0,0.12); font-size: 0.9em; animation: fadeInSlide 0.4s ease-out forwards; opacity: 0; }"
".recommendation:nth-child(1) { animation-delay: 0s; }"
".recommendation:nth-child(2) { animation-delay: 0.15s; }"
".recommendation:nth-child(3) { animation-delay: 0.3s; }"
".recommendation.best { background: linear-gradient(135deg, #fff9c4 0%, #ffeb3b 100%); border-left: 4px solid #f57c00; animation: fadeInSlide 0.4s ease-out forwards, subtlePulse 2s ease-in-out infinite; animation-delay: 0s, 0.5s; }"
"@keyframes fadeInSlide { from { opacity: 0; transform: translateY(-12px); } to { opacity: 1; transform: translateY(0); } }"
"@keyframes subtlePulse { 0%, 100% { box-shadow: 0 2px 6px rgba(245, 124, 0, 0.2); } 50% { box-shadow: 0 4px 12px rgba(245, 124, 0, 0.45); } }"
".rec-title { font-weight: bold; color: #333; margin-bottom: 4px; font-size: 0.95em; }"
".rec-ev { color: #667eea; font-size: 0.85em; font-weight: 600; }"
".total-score { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 10px; border-radius: 10px; text-align: center; font-size: 1.1em; font-weight: bold; margin-top: 10px; }"
"@media (max-width: 1000px) { .container { grid-template-columns: 1fr; } }"
".scoring-mode { text-align: center; color: #ff6b6b; font-size: 1em; font-weight: bold; margin: 10px 0; }"
".picker-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.5); display: none; align-items: center; justify-content: center; z-index: 999; }"
".picker-dialog { background: #ffffff; border-radius: 20px; padding: 28px; width: 340px; box-shadow: 0 10px 30px rgba(0,0,0,0.4); text-align: center; animation: popIn 0.2s ease-out; }"
"@keyframes popIn { from { opacity: 0; transform: scale(0.95); } to { opacity: 1; transform: scale(1); } }"
".picker-title { font-weight: bold; margin-bottom: 20px; color: #764ba2; font-size: 1.4em; }"
".picker-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; margin-bottom: 18px; }"
".picker-btn { padding: 24px; font-size: 2.5em; border-radius: 14px; border: 3px solid #764ba2; background: linear-gradient(135deg, #fff 0%, #f7f5ff 100%); cursor: pointer; transition: all 0.15s; font-weight: bold; color: #764ba2; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }"
".picker-btn:active { transform: scale(0.92); background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-color: #667eea; }"
".picker-cancel { padding: 14px 24px; font-size: 1.1em; border-radius: 10px; border: 2px solid #ccc; background: #f5f5f5; cursor: pointer; font-weight: bold; color: #666; }"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='game-area'>"
"<div class='recommendations-top'>"
"<h2>Strategy Recommendation</h2>"
"<div id='recommendationsContainer'>"
"<p style='text-align: center; color: #999; font-size: 0.95em;'>Enter your dice to see the optimal strategy!</p>"
"</div></div>"
"<h1>Yahtzee Strategy Helper</h1>"
"<div class='roll-info' id='rollInfo'>Tap a die to select its value (1-6)</div>"
"<div class='dice-container' id='diceContainer'></div>"
"<div class='controls'>"
"<button class='roll-btn' id='analyzeBtn' onclick='analyzeRoll()' style='display: none;'>Analyze Roll</button>"
"<button class='roll-btn' id='nextRollBtn' onclick='nextRoll()' style='display: none;'>Next Roll</button>"
"<button class='roll-btn' id='doneBtn' onclick='finishRolling()' style='display: none;'>Done Rolling - Score It</button>"
"<button class='new-game-btn' onclick='newGame()'>New Game</button>"
"<button class='clear-btn' onclick='clearDice()' id='clearBtn'>Clear Dice</button>"
"</div>"
"<div id='scoringMode' style='display: none;' class='scoring-mode'>Choose where to score on the scorecard</div>"
"</div>"
"<div class='sidebar'>"
"<div class='scorecard'>"
"<h2>Scorecard</h2>"
"<div class='bonus-tracker'>"
"<div style='font-weight: bold; margin-bottom: 2px;'>Upper Section Bonus</div>"
"<div id='bonusText'>0 / 63 points</div>"
"<div class='bonus-progress'><div class='bonus-fill' id='bonusFill'></div></div>"
"</div>"
"<div class='score-section'><h3>UPPER SECTION</h3>"
"<div class='score-row' data-category='ones'><span class='score-name'>Ones</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='twos'><span class='score-name'>Twos</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='threes'><span class='score-name'>Threes</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='fours'><span class='score-name'>Fours</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='fives'><span class='score-name'>Fives</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='sixes'><span class='score-name'>Sixes</span><span class='score-value'>-</span></div>"
"</div>"
"<div class='score-section'><h3>LOWER SECTION</h3>"
"<div class='score-row' data-category='threeOfKind'><span class='score-name'>3 of a Kind</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='fourOfKind'><span class='score-name'>4 of a Kind</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='fullHouse'><span class='score-name'>Full House</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='smallStraight'><span class='score-name'>Small Straight</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='largeStraight'><span class='score-name'>Large Straight</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='yahtzee'><span class='score-name'>YAHTZEE</span><span class='score-value'>-</span></div>"
"<div class='score-row' data-category='chance'><span class='score-name'>Chance</span><span class='score-value'>-</span></div>"
"</div>"
"<div class='total-score'>Total: <span id='totalScore'>0</span></div>"
"</div></div></div>"
"<div id='pickerOverlay' class='picker-overlay'>"
"<div class='picker-dialog' onclick='event.stopPropagation();'>"
"<div class='picker-title'>Select die value</div>"
"<div class='picker-grid'>"
"<button class='picker-btn' onclick='setDieValue(1)'>1</button>"
"<button class='picker-btn' onclick='setDieValue(2)'>2</button>"
"<button class='picker-btn' onclick='setDieValue(3)'>3</button>"
"<button class='picker-btn' onclick='setDieValue(4)'>4</button>"
"<button class='picker-btn' onclick='setDieValue(5)'>5</button>"
"<button class='picker-btn' onclick='setDieValue(6)'>6</button>"
"</div>"
"<button class='picker-cancel' onclick='closePicker()'>Cancel</button>"
"</div></div>"
"<script>"
"var gameState={dice:[0,0,0,0,0],held:[false,false,false,false,false],rollNumber:0,scorecard:{},upperSectionTotal:0,totalScore:0};"
"var diceDivs=[],holdButtons=[],recommendationsContainer,rollInfoEl,analyzeBtn,nextRollBtn,doneBtn,bonusFill,bonusText,totalScoreEl,pickerOverlay,currentPickerIndex=null;"
"function initUI(){"
"var diceContainer=document.getElementById('diceContainer');"
"rollInfoEl=document.getElementById('rollInfo');"
"recommendationsContainer=document.getElementById('recommendationsContainer');"
"analyzeBtn=document.getElementById('analyzeBtn');"
"nextRollBtn=document.getElementById('nextRollBtn');"
"doneBtn=document.getElementById('doneBtn');"
"bonusFill=document.getElementById('bonusFill');"
"bonusText=document.getElementById('bonusText');"
"totalScoreEl=document.getElementById('totalScore');"
"pickerOverlay=document.getElementById('pickerOverlay');"
"pickerOverlay.addEventListener('click',function(){closePicker();});"
"for(var i=0;i<5;i++){"
"var wrapper=document.createElement('div');"
"wrapper.className='die-wrapper';"
"var die=document.createElement('div');"
"die.className='die empty';"
"die.dataset.index=i;"
"die.textContent='?';"
"die.addEventListener('click',function(idx){return function(){openPicker(idx);};}(i));"
"var holdBtn=document.createElement('button');"
"holdBtn.className='hold-toggle';"
"holdBtn.textContent='Hold';"
"holdBtn.addEventListener('click',function(idx){return function(e){e.stopPropagation();toggleHold(idx);};}(i));"
"wrapper.appendChild(die);wrapper.appendChild(holdBtn);"
"diceContainer.appendChild(wrapper);"
"diceDivs.push(die);holdButtons.push(holdBtn);}"
"updateDisplay();}"
"function openPicker(index){currentPickerIndex=index;pickerOverlay.style.display='flex';}"
"function closePicker(){pickerOverlay.style.display='none';currentPickerIndex=null;}"
"function setDieValue(value){if(currentPickerIndex===null)return;gameState.dice[currentPickerIndex]=value;updateDiceVisual(currentPickerIndex);var lastIndex=currentPickerIndex;closePicker();checkAllDiceEntered();autoAdvanceToNextDie(lastIndex);}"
"function autoAdvanceToNextDie(currentIndex){for(var i=currentIndex+1;i<5;i++){if(gameState.dice[i]===0){setTimeout(function(idx){return function(){openPicker(idx);};}(i),200);return;}}}"
"function newGame(){gameState={dice:[0,0,0,0,0],held:[false,false,false,false,false],rollNumber:0,scorecard:{},upperSectionTotal:0,totalScore:0};document.querySelectorAll('.score-row').forEach(function(row){row.classList.remove('filled','available');row.querySelector('.score-value').textContent='-';row.onclick=null;});clearDice();document.getElementById('scoringMode').style.display='none';recommendationsContainer.innerHTML='<p style=\"text-align: center; color: #999; font-size: 0.95em;\">Enter your dice to see the optimal strategy!</p>';}"
"function toggleHold(index){gameState.held[index]=!gameState.held[index];updateDiceVisual(index);}"
"function clearDice(){gameState.dice=[0,0,0,0,0];gameState.held=[false,false,false,false,false];analyzeBtn.style.display='none';nextRollBtn.style.display='none';doneBtn.style.display='none';rollInfoEl.textContent='Tap a die to select its value (1-6)';recommendationsContainer.innerHTML='<p style=\"text-align: center; color: #999; font-size: 0.95em;\">Enter your dice to see the optimal strategy!</p>';for(var i=0;i<5;i++){updateDiceVisual(i);}updateBonusTracker();updateTotalScore();}"
"function checkAllDiceEntered(){var allSet=gameState.dice.every(function(d){return d>0;});if(allSet){analyzeBtn.style.display='inline-block';rollInfoEl.textContent='All dice set. Tap \"Analyze Roll\" to see recommendations.';}else{analyzeBtn.style.display='none';rollInfoEl.textContent='Tap a die to select its value (1-6)';}}"
"function analyzeRoll(){if(!gameState.dice.every(function(d){return d>0;})){alert('Please enter all 5 dice first!');return;}if(gameState.rollNumber<3){gameState.rollNumber++;}generateRecommendations();if(gameState.rollNumber<3){nextRollBtn.style.display='inline-block';doneBtn.style.display='inline-block';rollInfoEl.textContent='Roll '+gameState.rollNumber+'/3 - You can roll again or score now.';}else{nextRollBtn.style.display='none';doneBtn.style.display='inline-block';rollInfoEl.textContent='Final roll (3/3). Tap \"Done Rolling - Score It\" to score.';}}"
"function nextRoll(){for(var i=0;i<5;i++){if(!gameState.held[i]){gameState.dice[i]=0;}}analyzeBtn.style.display='none';nextRollBtn.style.display='none';doneBtn.style.display='none';for(var i=0;i<5;i++){updateDiceVisual(i);}rollInfoEl.textContent='Enter dice for roll '+(gameState.rollNumber+1)+'/3, then tap \"Analyze Roll\".';recommendationsContainer.innerHTML='<p style=\"text-align: center; color: #999; font-size: 0.95em.\">Enter your dice to see the optimal strategy!</p>';updateBonusTracker();updateTotalScore();}"
"function finishRolling(){if(!gameState.dice.every(function(d){return d>0;})){alert('Please enter all 5 dice first!');return;}analyzeBtn.style.display='none';nextRollBtn.style.display='none';doneBtn.style.display='none';enterScoringMode();}"
"function updateDiceVisual(i){var val=gameState.dice[i];var held=gameState.held[i];var die=diceDivs[i];var holdBtn=holdButtons[i];if(val===0){die.className='die empty';die.textContent='?';}else{die.className='die'+(held?' kept':'');die.textContent=val;}holdBtn.className='hold-toggle'+(held?' held':'');holdBtn.textContent=held?'Held':'Hold';}"
"function updateDisplay(){for(var i=0;i<5;i++){updateDiceVisual(i);}updateBonusTracker();updateTotalScore();}"
"function enterScoringMode(){document.getElementById('scoringMode').style.display='block';rollInfoEl.textContent='Choose where to score on the scorecard';var availableScores=calculateAllScores(gameState.dice);document.querySelectorAll('.score-row').forEach(function(row){var category=row.dataset.category;row.onclick=null;row.classList.remove('available');if(!gameState.scorecard[category]){row.classList.add('available');var score=availableScores[category]||0;row.querySelector('.score-value').textContent=score;row.onclick=function(){scoreCategory(category,score);};}});generateScoringRecommendations(availableScores);}"
"function scoreCategory(category,score){gameState.scorecard[category]=score;if(['ones','twos','threes','fours','fives','sixes'].indexOf(category)!==-1){gameState.upperSectionTotal+=score;}var row=document.querySelector('[data-category=\"'+category+'\"]');row.classList.remove('available');row.classList.add('filled');row.onclick=null;document.querySelectorAll('.score-row').forEach(function(r){if(!gameState.scorecard[r.dataset.category]){r.classList.remove('available');r.onclick=null;r.querySelector('.score-value').textContent='-';}});gameState.rollNumber=0;clearDice();document.getElementById('scoringMode').style.display='none';if(Object.keys(gameState.scorecard).length===13){setTimeout(function(){var finalScore=gameState.totalScore+(gameState.upperSectionTotal>=63?35:0);alert('Game Over! Final Score: '+finalScore);},50);}}"
"function calculateAllScores(dice){var counts=[0,0,0,0,0,0,0];dice.forEach(function(d){counts[d]++;});var sum=dice.reduce(function(a,b){return a+b;},0);return{ones:counts[1]*1,twos:counts[2]*2,threes:counts[3]*3,fours:counts[4]*4,fives:counts[5]*5,sixes:counts[6]*6,threeOfKind:counts.some(function(c){return c>=3;})?sum:0,fourOfKind:counts.some(function(c){return c>=4;})?sum:0,fullHouse:(counts.indexOf(3)!==-1&&counts.indexOf(2)!==-1)||counts.indexOf(5)!==-1?25:0,smallStraight:hasSmallStraight(dice)?30:0,largeStraight:hasLargeStraight(dice)?40:0,yahtzee:counts.some(function(c){return c===5;})?50:0,chance:sum};}"
"function hasSmallStraight(dice){var unique=Array.from(new Set(dice)).sort(function(a,b){return a-b;});var str=unique.join('');return str.indexOf('1234')!==-1||str.indexOf('2345')!==-1||str.indexOf('3456')!==-1;}"
"function hasLargeStraight(dice){var sorted=dice.slice().sort().join('');return sorted==='12345'||sorted==='23456';}"
"function updateBonusTracker(){var progress=Math.min(100,(gameState.upperSectionTotal/63)*100)||0;bonusFill.style.width=progress+'%';bonusText.textContent=gameState.upperSectionTotal+' / 63 points';}"
"function updateTotalScore(){var total=0;for(var key in gameState.scorecard){total+=gameState.scorecard[key];}if(gameState.upperSectionTotal>=63){total+=35;}gameState.totalScore=total;totalScoreEl.textContent=total;}"
"function rollsLeft(){return Math.max(0,3-gameState.rollNumber);}"
"function yahtzeeSuccessProb(currentCount){var R=rollsLeft();var missing=5-currentCount;if(missing<=0)return 1;if(R<=0)return 0;var pOneDie=1-Math.pow(5/6,R);return Math.pow(pOneDie,missing);}"
"function generateRecommendations(){var recommendations=[];var dice=gameState.dice;var counts=[0,0,0,0,0,0,0];dice.forEach(function(d){counts[d]++;});var hasYahtzee=counts.some(function(c){return c===5;});var hasFourKind=counts.some(function(c){return c>=4;});var hasThreeKind=counts.some(function(c){return c>=3;});var hasPair=counts.some(function(c){return c>=2;});var hasLarge=hasLargeStraight(dice);var hasSmall=hasSmallStraight(dice);var sumDice=dice.reduce(function(a,b){return a+b;},0);var R=rollsLeft();if(hasYahtzee&&!gameState.scorecard.yahtzee){recommendations.push({action:'Keep all dice - You have YAHTZEE! (50 pts)',ev:50,priority:1});}else if(hasFourKind){var fourValue=counts.findIndex(function(c){return c>=4;});var currentCount=counts[fourValue];var p=yahtzeeSuccessProb(currentCount);var evYahtzee=50*p;if(!gameState.scorecard.yahtzee&&R>0){recommendations.push({action:'Keep all four '+fourValue+'s, reroll 1 die - Go for Yahtzee (p = '+(p*100).toFixed(1)+'%)',ev:evYahtzee,priority:1});}if(!gameState.scorecard.fourOfKind){recommendations.push({action:'Lock in 4 of a Kind now ('+sumDice+' pts)',ev:sumDice,priority:2});}}else if(hasLarge&&!gameState.scorecard.largeStraight){recommendations.push({action:'Keep all dice - Large Straight (40 pts)!',ev:40,priority:1});}else if(hasSmall){if(!gameState.scorecard.smallStraight){recommendations.push({action:'Keep straight sequence - Small Straight (30 pts)',ev:30,priority:1});}if(!gameState.scorecard.largeStraight&&R>0){recommendations.push({action:'Try for Large Straight - reroll non-sequential dice',ev:40,priority:2});}}else if(hasThreeKind){var threeValue=counts.findIndex(function(c){return c>=3;});var currentCount=counts[threeValue];var pYahtzee=yahtzeeSuccessProb(currentCount);var evYahtzee=50*pYahtzee;if(!gameState.scorecard.yahtzee&&R>0){recommendations.push({action:'Keep three '+threeValue+'s - Try for Yahtzee/4-of-a-kind (p = '+(pYahtzee*100).toFixed(1)+'%)',ev:evYahtzee,priority:1});}var pairCount=counts.filter(function(c){return c>=2;}).length;if(pairCount>=2&&!gameState.scorecard.fullHouse){recommendations.push({action:'Keep all - You have Full House (25 pts)!',ev:25,priority:2});}else if(!gameState.scorecard.fullHouse&&R>0){recommendations.push({action:'Keep three '+threeValue+'s - Try for Full House',ev:25,priority:3});}}else if(hasPair){var pairValue=counts.findIndex(function(c){return c>=2;});var highDice=dice.filter(function(d){return d>=4;});if(highDice.length>=3&&gameState.upperSectionTotal<63){recommendations.push({action:'Keep high dice (4-6) - Build toward upper bonus',ev:20,priority:1});}recommendations.push({action:'Keep pair of '+pairValue+'s - Try for 3-of-a-kind',ev:16,priority:2});}else{var highDice=dice.filter(function(d){return d>=4;});if(highDice.length>=2){recommendations.push({action:'Keep '+highDice.length+' high dice (4-6) - Solid Chance/upper base',ev:15,priority:2});}recommendations.push({action:'Reroll all - fresh shot at high roll',ev:17.5,priority:3});}recommendations.sort(function(a,b){return a.priority-b.priority||b.ev-a.ev;});displayRecommendations(recommendations.slice(0,3));}"
"function generateScoringRecommendations(availableScores){var recommendations=[];var needsBonus=gameState.upperSectionTotal<63;if(availableScores.yahtzee===50&&!gameState.scorecard.yahtzee){recommendations.push({action:'YAHTZEE - 50 points!',ev:50,priority:1});}if(availableScores.largeStraight===40&&!gameState.scorecard.largeStraight){recommendations.push({action:'Large Straight - 40 points',ev:40,priority:1});}if(availableScores.smallStraight===30&&!gameState.scorecard.smallStraight){recommendations.push({action:'Small Straight - 30 points',ev:30,priority:2});}if(availableScores.fullHouse===25&&!gameState.scorecard.fullHouse){recommendations.push({action:'Full House - 25 points',ev:25,priority:2});}var upperCats=['sixes','fives','fours','threes','twos','ones'];for(var i=0;i<upperCats.length;i++){var cat=upperCats[i];var score=availableScores[cat];if(!gameState.scorecard[cat]&&score>=12){var bonusBump=needsBonus?3:0;var bonusText=needsBonus?' (helps push to +35 bonus)':'';recommendations.push({action:cat.charAt(0).toUpperCase()+cat.slice(1)+' - '+score+' pts'+bonusText,ev:score+bonusBump,priority:2});break;}}if(availableScores.fourOfKind>20&&!gameState.scorecard.fourOfKind){recommendations.push({action:'4 of a Kind - '+availableScores.fourOfKind+' pts',ev:availableScores.fourOfKind,priority:3});}if(availableScores.threeOfKind>15&&!gameState.scorecard.threeOfKind){recommendations.push({action:'3 of a Kind - '+availableScores.threeOfKind+' pts',ev:availableScores.threeOfKind,priority:3});}if(!gameState.scorecard.chance&&availableScores.chance>20){recommendations.push({action:'Chance - '+availableScores.chance+' pts (solid fallback)',ev:availableScores.chance,priority:3});}if(recommendations.length<2){recommendations.push({action:'Consider taking a 0 in a low-priority category',ev:0,priority:4});}recommendations.sort(function(a,b){return a.priority-b.priority||b.ev-a.ev;});displayRecommendations(recommendations.slice(0,3));}"
"function displayRecommendations(recommendations){recommendationsContainer.innerHTML='';for(var i=0;i<recommendations.length;i++){var rec=recommendations[i];var div=document.createElement('div');div.className='recommendation'+(i===0?' best':'');var emoji='';if(i===0)emoji='BEST: ';else if(i===1)emoji='GOOD: ';else emoji='OPTION: ';var title=document.createElement('div');title.className='rec-title';title.textContent=emoji+rec.action;var ev=document.createElement('div');ev.className='rec-ev';ev.textContent='EV: ~'+rec.ev.toFixed(1)+' points';div.appendChild(title);div.appendChild(ev);recommendationsContainer.appendChild(div);}}"
"initUI();"
"</script>"
"</body>"
"</html>")

wv = ui.WebView()
wv.name = 'Yahtzee Strategy Helper'
wv.load_html(html)
wv.present('fullscreen')
